services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      # <— Note the authSource=admin here
      MONGO_URI: "mongodb://admin:secret@mongo:27017/bookstore?authSource=admin"
    ports:
      - "3000:3000"
      - "5173:5173"

volumes:
  mongo-data:

#docker-compose down
#docker-compose up --build -d
